# services:
#   sqlserver:
#     image: mcr.microsoft.com/mssql/server:2019-latest
#     platform: linux/amd64
#     container_name: bepatient-sqlserver
#     environment:
#       ACCEPT_EULA: "Y"
#       SA_PASSWORD: "Your_strong_Password123"
#       MSSQL_PID: "Developer"
#     ports:
#       - "1433:1433"
#     volumes:
#       - ./sqlserver-data:/var/opt/mssql

services:
  sqlserver:
    # image: mcr.microsoft.com/mssql/server:2019-latest
    image: mcr.microsoft.com/mssql/server:2025-latest
    # platform: linux/amd64
    container_name: bepatient-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_strong_Password123"
      MSSQL_PID: "Developer"
    ports:
      - "1400:1433"
    volumes:
      - ./sqlserver-data:/var/opt/mssql
    restart: unless-stopped